- name: Download JAR from JFrog Artifactory and Deploy
  hosts: localhost
  become: true  # Run tasks as a superuser

  vars:
    jfrog_artifactory_url: "https://devopsansible.jfrog.io/artifactory/coffeeshop/nl/brianvermeer/workshop/coffeeShop/2.6.0/coffeeShop-2.6.0.jar"
    # jfrog_repository: "coffeeshop"  # Updated repository name
    # artifact_path: "nl/brianvermeer/workshop/coffeeShop/2.6.0/"
    download_destination: "/home/ansible"
    api_key: "AKCp8pRjbpVpeC3aKfFCU1WREzZUHBXKDpo1jq4PqQ2P5qcbVtPoYegFJnLV12U9LXmS4voYd"
    username: "aravindrekha1504@gmail.com"
    # deploy_directory: "/home/vanjimuthu_palani"
    # app_command: "nohup java -jar {{ deploy_directory }}/coffeeShop-2.6.0.jar"
    # download_required: true  # Added default value for clarity
    # start_command_required: true  # Added default value for clarity

  tasks:
    - name: "just execute a ls -lrt command"
      shell: "pwd & mkdir testvanji"
    # - name: Download JAR from JFrog Artifactory
    #   ansible.builtin.uri:
    #     url: "{{ jfrog_artifactory_url }}"
    #     dest: "{{ download_destination }}/coffeeShop-2.6.0.jar"
    #     headers:
    #       "Authorization": "Basic {{ (username + ':' + api_key) | b64encode }}"
    #     method: GET
    #   when: not ansible_check_mode  # Skip in check mode
