- name: Download JAR from JFrog Artifactory and Deploy
  hosts: tower_poc_target_ubuntu_svr
  become: true  # Run tasks as a superuser

  vars:
    jfrog_artifactory_url: "https://devopsansible.jfrog.io/artifactory/coffeeshop/nl/brianvermeer/workshop/coffeeShop/2.6.0/coffeeShop-2.6.0.jar"
    # jfrog_repository: "coffeeshop"  # Updated repository name
    # artifact_path: "nl/brianvermeer/workshop/coffeeShop/2.6.0/"
    download_destination: "/home/vanjimuthu_palani"
    api_key: "AKCp8pRjbpVpeC3aKfFCU1WREzZUHBXKDpo1jq4PqQ2P5qcbVtPoYegFJnLV12U9LXmS4voYd"
    username: "aravindrekha1504@gmail.com"
    # deploy_directory: "/home/vanjimuthu_palani"
    # app_command: "nohup java -jar {{ deploy_directory }}/coffeeShop-2.6.0.jar"
    # download_required: true  # Added default value for clarity
    # start_command_required: true  # Added default value for clarity

  tasks:
  #   - name: Create deploy directory if not exist
  #     ansible.builtin.file:
  #       path: "{{ deploy_directory }}"
  #       state: directory

    - name: Download JAR from JFrog Artifactory
      ansible.builtin.uri:
        url: "{{ jfrog_artifactory_url }}"
        dest: "{{ download_destination }}"
        headers:
          "Authorization": "Basic {{ (username + ':' + api_key) | b64encode }}"
        method: GET
      ignore_errors: yes
      register: download_result

    - debug:
        var: download_result
